"""branch C3Sevents14001

Revision ID: 20a901f9c82c
Revises: None
Create Date: 2014-07-15 02:11:28.526420

"""

# revision identifiers, used by Alembic.
revision = '20a901f9c82c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('discount', sa.Float(), nullable=True))
    op.add_column('tickets', sa.Column('guestlist', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('rep_city', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('rep_country', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('rep_firstname', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('rep_lastname', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('rep_street', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('rep_type', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('rep_zip', sa.Text(), nullable=True))
    op.add_column('tickets', sa.Column('ticket_all', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('ticket_bc_attendance', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('ticket_bc_buffet', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('ticket_gv_attendance', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('ticket_tshirt', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('ticket_tshirt_size', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('ticket_tshirt_type', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('token', sa.Text(), nullable=True))
    #op.drop_column('tickets', 'ticket_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ticket_type', sa.INTEGER(), nullable=True))
    op.drop_column('tickets', 'token')
    op.drop_column('tickets', 'ticket_tshirt_type')
    op.drop_column('tickets', 'ticket_tshirt_size')
    op.drop_column('tickets', 'ticket_tshirt')
    op.drop_column('tickets', 'ticket_gv_attendance')
    op.drop_column('tickets', 'ticket_bc_buffet')
    op.drop_column('tickets', 'ticket_bc_attendance')
    op.drop_column('tickets', 'ticket_all')
    op.drop_column('tickets', 'rep_zip')
    op.drop_column('tickets', 'rep_type')
    op.drop_column('tickets', 'rep_street')
    op.drop_column('tickets', 'rep_lastname')
    op.drop_column('tickets', 'rep_firstname')
    op.drop_column('tickets', 'rep_country')
    op.drop_column('tickets', 'rep_city')
    op.drop_column('tickets', 'guestlist')
    op.drop_column('tickets', 'discount')
    ### end Alembic commands ###
