"""membership_type

Revision ID: 3652e5db691
Revises: 44222822b23a
Create Date: 2014-07-17 15:15:48.273162

"""

# revision identifiers, used by Alembic.
revision = '3652e5db691'
down_revision = '44222822b23a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('membership_type', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'membership_type')
    ### end Alembic commands ###
