"""cashiers_comment added

Revision ID: 4cc91fa8a65a
Revises: 4dfdc407c235
Create Date: 2014-08-20 08:09:36.938059

"""

# revision identifiers, used by Alembic.
revision = '4cc91fa8a65a'
down_revision = '4dfdc407c235'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('cashiers_comment', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'cashiers_comment')
    ### end Alembic commands ###
