"""represents_ids added

Revision ID: 4dfdc407c235
Revises: 4e14a1928ce6
Create Date: 2014-08-19 07:22:31.176204

"""

# revision identifiers, used by Alembic.
revision = '4dfdc407c235'
down_revision = '4e14a1928ce6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('represents_id1', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('represents_id2', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'represents_id2')
    op.drop_column('tickets', 'represents_id1')
    ### end Alembic commands ###
