"""staff_comment added

Revision ID: 4e14a1928ce6
Revises: 81f0ef26842
Create Date: 2014-08-15 03:22:50.828204

"""

# revision identifiers, used by Alembic.
revision = '4e14a1928ce6'
down_revision = '81f0ef26842'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('staff_comment', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'staff_comment')
    ### end Alembic commands ###
