"""checked in times added

Revision ID: 567b3bbb0ffd
Revises: 4cc91fa8a65a
Create Date: 2014-08-20 12:29:20.428033

"""

# revision identifiers, used by Alembic.
revision = '567b3bbb0ffd'
down_revision = '4cc91fa8a65a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('checked_bc_time', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('checked_gv_time', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('received_extra1_time', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('received_extra2_time', sa.DateTime(), nullable=True))
    op.add_column('tickets', sa.Column('received_extra3_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'received_extra3_time')
    op.drop_column('tickets', 'received_extra2_time')
    op.drop_column('tickets', 'received_extra1_time')
    op.drop_column('tickets', 'checked_gv_time')
    op.drop_column('tickets', 'checked_bc_time')
    ### end Alembic commands ###
