"""representative email

Revision ID: 5714361945d4
Revises: 3652e5db691
Create Date: 2014-07-20 15:58:19.380765

"""

# revision identifiers, used by Alembic.
revision = '5714361945d4'
down_revision = '3652e5db691'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('rep_email', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'rep_email')
    ### end Alembic commands ###
