"""added flags for recieved extras; added guestlist_bc and guestlist_gv for guestlist categories

Revision ID: 81f0ef26842
Revises: 5714361945d4
Create Date: 2014-08-15 02:34:44.314271

"""

# revision identifiers, used by Alembic.
revision = '81f0ef26842'
down_revision = '5714361945d4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('checked_bc', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('checked_gv', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('guestlist_bc', sa.Unicode(length=255), nullable=True))
    op.add_column('tickets', sa.Column('guestlist_gv', sa.Unicode(length=255), nullable=True))
    op.add_column('tickets', sa.Column('received_extra1', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('received_extra2', sa.Boolean(), nullable=True))
    op.add_column('tickets', sa.Column('received_extra3', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'received_extra3')
    op.drop_column('tickets', 'received_extra2')
    op.drop_column('tickets', 'received_extra1')
    op.drop_column('tickets', 'guestlist_gv')
    op.drop_column('tickets', 'guestlist_bc')
    op.drop_column('tickets', 'checked_gv')
    op.drop_column('tickets', 'checked_bc')
    ### end Alembic commands ###
